title:              Dan Harrison
email:              87bdharr@gmail.com
description:        Cyber Security Consultant. Data Enthusiast. Pilot.
author:             Dan Harrison
baseurl:            ""
url:                "www.danharrison.me.uk"

# Social Profiles
twitter_username:   
github_username:  87bdharr
medium_username: 87bdharr
linkedin_username: daniel-harrison-13830292

# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
